name: docker-develop

on:
  workflow_dispatch:
  push:
    branches: develop

jobs:
  multi-registries:
    runs-on: ubuntu-latest
    steps:
      -
        name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 58368
          swap-size-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            cameronraysmith/notebooks:develop
            ghcr.io/cameronraysmith/notebooks:develop
            gcr.io/${{ secrets.GCR_PROJECT_ID }}/notebooks:develop
